[package]
name = "tlserver"
version = "0.1.0"
authors = ["matt-hu <matt.hu1@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.13.0"
serde_json = "1.0.64"
serial = "0.4"
