name: Build Rust

on:
  workflow_dispatch:
  release:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
          fail-fast: false
          matrix:
            config:

            - name: Linux
              os: ubuntu-latest

            - name: macOS_Intel
              os: macos-latest

            - name: Windows
              os: windows-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --release --verbose
      
    - name: Run tests
      run: cargo test --verbose
    
    - name: Build .deb
      if: startswith( matrix.config.os, 'ubuntu' ) && (github.event_name == 'release' || github.event_name == 'workflow_dispatch')
      run: |
        cargo install cargo-deb
        cargo deb
      
    - uses: actions/upload-artifact@v2
      with:
        name: tlserver_${{ matrix.config.name }}_${{ github.run_id }}
        path: target/ # or path/to/artifact
